// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwvvahpaszgpoedhlkxy.supabase.co" || import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3dnZhaHBhc3pncG9lZGhsa3h5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MjA5ODYsImV4cCI6MjA3NDQ5Njk4Nn0._BbYYvaMdvZMaX47-tGUvcVTgOsgi0aBxoU5MBTIx2o" || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});